apiVersion: apps/v1
kind: Deployment
metadata:
  name: distant-backend-2-deployment  # Nom du déploiement
  labels:
    app: distant-backend-2             # Label pour identifier ce déploiement
spec:
  replicas: {{.Values.replicaCountMax}}                         # Nombre d'instances à maintenir (haute disponibilité)
  selector:
    matchLabels:
      app: distant-backend-2           # Sélectionne les pods avec ce label
  template:
    metadata:
      labels:
        app: distant-backend-2         # Label appliqué aux pods créés
    spec:
      containers:
        - name: distant-backend        # Nom du conteneur
          image: localhost:5001/distant-backend:latest  # Image Docker du service
          ports:
            - containerPort: 3002      # Port exposé par le conteneur
          env:
            - name: TOKEN
              value: {{ .Values.app.token | quote }}
            - name: UPLOAD_DIR
              value: {{ .Values.app.uploadDir | quote }}

