apiVersion: v2
name: minio-s3-tada
description: A Helm chart for Kubernetes

type: application
version: 0.1.0

appVersion: '0.1.0'
dependencies:
    - name: tada
      version: 1.2.58-main
      repository: oci://registry-1.docker.io/bouyguestelecomcharts