# eslint-disable
# prettier-ignore
apiVersion: batch/v1
kind: CronJob
metadata:
  name: tada-{{ .Release.Name }}-backup-and-clean
spec:
  schedule: '0 0 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: remove-expired-files-cronjob
              image: '{{ .Values.backupAndCleanJob.imageName }}:{{ .Values.backupAndCleanJob.imageVersion }}'
              resources:
                requests:
                      cpu: {{ .Values.backupAndCleanJob.resources.requests.cpu }}
                      memory: {{ .Values.backupAndCleanJob.resources.requests.memory }}
              env:
                - name: API_SERVICE
                  value: "{{ include "mediaService" . }}"
                - name: CATALOG_ROUTE
                  value: '{{ .Values.mediaApi.routes.catalog.get }}'
                - name: DEV_ENV
                  value: '{{ .Values.dev }}'
                - name: NGINX_SERVICE
                  value: "{{ include "nginxService" . }}"
                - name: API_PREFIX
                  value: '{{ .Values.mediaApi.apiPrefix }}'
                - name: DELEGATED_STORAGE_METHOD
                  value: '{{ .Values.mediaApi.backupStorageMethod }}'
          restartPolicy: Never
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
