# eslint-disable
# prettier-ignore
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-and-clean-cronjob-{{ .Values.version }}
spec:
  schedule: '0 0 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: {{ .Values.imagePullSecrets.name }}
          containers:
            - name: remove-expired-files-cronjob
              image: '{{ .Values.mediaProvider.backupAndCleanJob.imageName }}:{{ .Values.mediaProvider.backupAndCleanJob.imageVersion }}'
              volumeMounts:
                - name: logs
                  mountPath: "/logs"
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
              env:
                - name: API_SERVICE
                  value: '{{ .Values.mediaProvider.service }}'
                - name: CATALOG_ROUTE
                  value: '{{ .Values.mediaProvider.routes.catalog.get }}'
                - name: DEV_ENV
                  value: '{{ .Values.dev }}'
                - name: IMAGE_SERVICE
                  value: '{{ .Values.mediaProvider.service }}'
                - name: API_PREFIX
                  value: '{{ .Values.mediaProvider.apiPrefix }}'
                - name: DELEGATED_STORAGE_METHOD
                  value: '{{ .Values.mediaProvider.backupStorageMethod }}'
                - name: GET_ROUTE
                  value: '{{ .Values.mediaProvider.routes.files.get }}'
                - name: PATCH_ROUTE
                  value: '{{ .Values.mediaProvider.routes.files.patch }}'
                - name: DELETE_ROUTE
                  value: '{{ .Values.mediaProvider.routes.files.delete }}'
          volumes:
            - name: logs
              emptyDir: {}
          restartPolicy: Never
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
