{{- if not .Values.local }}
  {{- if .Values.mediaApi.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: api-media-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: tada-{{ .Release.Name }}-media
    minReplicas: {{ .Values.mediaApi.hpa.replicaCountMin }}
    maxReplicas: {{ .Values.mediaApi.hpa.replicaCountMax }}
    metrics:
        -   type: Resource
            resource:
                name: memory
                target:
                    type: Utilization
                    averageUtilization: {{.Values.mediaApi.hpa.metrics.memory.averageUtilization}}
        -   type: Resource
            resource:
                name: cpu
                target:
                    type: Utilization
                    averageUtilization: {{.Values.mediaApi.hpa.metrics.cpu.averageUtilization}}
  {{- end }}
{{- end }}
