apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: tada-{{ .Release.Name }}-api-ingress
    annotations:
        {{- range $key, $value := .Values.ingress.api.annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
spec:
    ingressClassName: {{ .Values.ingress.api.className }}
    {{- if .Values.ingress.api.tls }}
    tls:
        -   hosts:
                - {{ .Values.env }}.api{{ .Values.domain }}
            secretName: tada-{{ .Release.Name }}-api-tls-certificate
    {{- end }}
    rules:
        - host: '{{.Values.env}}.api{{.Values.domain}}'
          http:
              paths:
                  - path: /
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: tada-{{ .Release.Name }}-media-service
                            port:
                                number: 80
