{{- if .Values.local }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tada-{{ .Release.Name }}-local-pv-redis
  labels:
    type:  tada-{{ .Release.Name }}-redis
spec:
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  local:
    path: "/tmp"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
                - orbstack
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name:  tada-{{ .Release.Name }}-redis-pv
    annotations:
        volume-expander-operator.redhat-cop.io/autoexpand: "true"
        volume-expander-operator.redhat-cop.io/polling-frequency: "1m"
        volume-expander-operator.redhat-cop.io/expand-threshold-percent: "80"
        volume-expander-operator.redhat-cop.io/expand-by-percent: "25"
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: "{{.Values.redis.storage.requestedStorage}}"
    storageClassName: "{{.Values.redis.storage.storageClassName}}"