apiVersion: apps/v1
kind: Deployment
metadata:
    name:  {{ .Release.Name }}-redis-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app:  {{ .Release.Name }}-redis
    template:
        metadata:
            labels:
                app:  {{ .Release.Name }}-redis
        spec:
            containers:
                - name:  {{ .Release.Name }}-redis
                  image: {{ .Values.redis.imageName }}
                  command:
                      - 'redis-server'
                      - '--protected-mode'
                      - 'no'
                      - '--dir'
                      - '/dumps'
                  ports:
                      - containerPort: 6379
                  volumeMounts:
                      - name: redis-storage
                        mountPath: /dumps
                  resources:
                    requests:
                      cpu: 200m
                      memory: 128Mi
                    limits:
                      cpu: 800m
                      memory: 512Mi
            volumes:
                - name: redis-storage
                  persistentVolumeClaim:
                      claimName:  {{ .Release.Name }}-redis-pv
