apiVersion: v1
kind: Service
metadata:
    name: tada-{{ .Release.Name }}-redis-service
spec:
    selector:
        app: tada-{{ .Release.Name }}-redis
    ports:
        - protocol: TCP
          port: 6379
          targetPort: 6379
