apiVersion: v1
kind: Service
metadata:
    name: tada-{{ .Release.Name }}-media-service
    labels:
        app: tada-{{ .Release.Name }}-media
spec:
    type: NodePort
    ports:
        - protocol: TCP
          name: http
          targetPort: 3001
          port: 80
    selector:
        app: tada-{{ .Release.Name }}-media
