apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-nginx-purge-configmap
data:
    proxy-body-size: 10m
    nginx.conf: |
        events {}

        http {
            log_format json escape=json
            '{'
            '"access_time":"$time_iso8601",'
            '"remote_addr":"$remote_addr",'
            '"method":"$request_method",'
            '"http_version":"HTTP/$http_version",'
            '"user_agent":"$http_user_agent",'
            '"url":"$request_uri",'
            '"referrer":"$http_referer",'
            '"response_code":$status,'
            '"body_byte_send":"$body_bytes_sent",'
            '"duration":"$request_time",'
            '"cache_status":"$upstream_cache_status"'
            '}';

            proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=zone2:10m max_size=1g inactive=24h use_temp_path=off;
            server {
              listen 8081;
              server_name {{ .Release.Name }}-nginx-purge;

              proxy_cache zone2;
              proxy_cache_key $request_uri;
              proxy_cache_valid 200 302 30d;
              proxy_cache_valid 404 1m;
              proxy_cache_methods GET;

              types {
                application/pdf pdf;
                image/svg+xml svg svgz;
                image/jpeg jpeg jpg;
                image/png png;
                image/webp webp;
              }

              location = /favicon.ico {
                return 204;
                access_log off;
                log_not_found off;
              }
              location {{ if hasKey .Values.mediaProvider "apiPrefix" }}{{ .Values.mediaProvider.apiPrefix }}/catalog{{ else }}/catalog{{ end }} {
                limit_except GET {
                    deny all;
                }
                proxy_cache_valid 200 302 0s;
                proxy_no_cache 1;
                proxy_cache_bypass 1;
                add_header X-Cache-Status $upstream_cache_status;
                proxy_pass {{ include "mediaService" . }};
              }

              location ~ ^{{ if hasKey .Values.mediaProvider "apiPrefix" }}{{ .Values.mediaProvider.apiPrefix }}{{ .Values.mediaProvider.routes.file.get }}{{ else }}{{ .Values.mediaProvider.routes.file.get }}{{ end }} {
                limit_except GET {
                    deny all;
                }
                add_header X-Cache-Status $upstream_cache_status;
                proxy_pass {{ include "mediaService" . }};
              }
                location ~ /purge(/.*) {
                   limit_except GET {
                       deny all;
                   }
                   proxy_cache_valid 200 302 0s;
                   proxy_no_cache 1;
                   proxy_cache_bypass 1;
                   proxy_cache_purge zone2 $1;
                }
              location / {
                return 200;
              }

              access_log /dev/stdout json;
              }
            }