apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
    labels:
        app: nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                -   name: nginx
                    image: bitnami/nginx:latest
                    ports:
                        -   containerPort: 8080
                    volumeMounts:
                        -   name: nginx-cache
                            mountPath: /opt/bitnami/nginx/cache
                        -   name: nginx-config-volume
                            mountPath: /opt/bitnami/nginx/conf/nginx.conf
                            subPath: nginx.conf
            volumes:
                -   name: nginx-cache
                    emptyDir: {}
                -   name: nginx-config-volume
                    configMap:
                        name: nginx-configmap
                        items:
                            -   key: nginx.conf
                                path: nginx.conf