apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-nginx-service
    labels:
        app: {{ .Release.Name }}-nginx
spec:
    type: NodePort
    ports:
        - protocol: TCP
          name: http
          targetPort: 8080
          port: 80
    selector:
        app: {{ .Release.Name }}-nginx
