apiVersion: v1
kind: Service
metadata:
    name: tada-{{ .Release.Name }}-nginx-purge-service
    labels:
        app: tada-{{ .Release.Name }}-nginx-purge
spec:
    type: NodePort
    ports:
        - protocol: TCP
          name: http
          targetPort: 8081
          port: 80
    selector:
        app: tada-{{ .Release.Name }}-nginx-purge
