apiVersion: apps/v1
kind: Deployment
metadata:
    name: tada-{{ .Release.Name }}-nginx-purge
    labels:
        app: tada-{{ .Release.Name }}-nginx-purge
spec:
    replicas: 1
    selector:
        matchLabels:
            app: tada-{{ .Release.Name }}-nginx-purge
    template:
        metadata:
            labels:
                app: tada-{{ .Release.Name }}-nginx-purge
        spec:
            containers:
                -   name: tada-{{ .Release.Name }}-nginx-purge
                    image: {{.Values.mediaProvider.nginxPurge.imageName}}
                    ports:
                        -   containerPort: 8081
                    volumeMounts:
                        -   name: nginx-purge-cache
                            mountPath: /var/cache/nginx
                        -   name: nginx-pid
                            mountPath: /var/run
                        -   name: nginx-config-volume
                            mountPath: /etc/nginx/nginx.conf
                            subPath: nginx.conf
                    resources:
                        requests:
                            cpu: {{ .Values.mediaProvider.nginxPurge.resources.requests.cpu }}
                            memory: {{ .Values.mediaProvider.nginxPurge.resources.requests.memory }}
                        limits:
                            cpu: {{ .Values.mediaProvider.nginxPurge.resources.limits.cpu }}
                            memory: {{ .Values.mediaProvider.nginxPurge.resources.limits.memory }}
            volumes:
                -   name: nginx-pid
                    emptyDir: {}
                -   name: nginx-purge-cache
                    emptyDir: {}
                -   name: nginx-config-volume
                    configMap:
                        name: "tada-{{ .Release.Name }}-nginx-purge-configmap"
                        items:
                            -   key: nginx.conf
                                path: nginx.conf
