apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: tada-{{ .Release.Name }}-nginx-ingress
    annotations:
    {{- range $key, $value := .Values.ingress.nginx.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
    ingressClassName: {{ .Values.ingress.nginx.className }}
    {{- if .Values.ingress.nginx.tls }}
    tls:
        -   hosts:
                - {{ .Values.env }}{{ .Values.domain }}
            secretName: tada-{{ .Release.Name }}-tls-certificate
    {{- end }}
    rules:
        -   host: '{{ .Values.env }}{{ .Values.domain }}'
            http:
                paths:
                    -   path: {{ if hasKey .Values.mediaApi "apiPrefix" }}{{ .Values.mediaApi.apiPrefix }}/assets/media/?${{ else }}/assets/media/?${{ end }}
                        pathType: ImplementationSpecific
                        backend:
                            service:
                                name: tada-{{ .Release.Name }}-nginx-service
                                port:
                                    number: 80
                    -   path: {{ if hasKey .Values.mediaApi "apiPrefix" }}{{ .Values.mediaApi.apiPrefix }}/catalog{{ else }}/catalog{{ end }}
                        pathType: ImplementationSpecific
                        backend:
                            service:
                                name: tada-{{ .Release.Name }}-nginx-service
                                port:
                                    number: 80
