apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: nginx-ingress
    annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
    ingressClassName: {{ .Values.ingress.className }}
    {{- if .Values.ingress.tls }}
    tls:
        -   hosts:
                - {{ .Values.env }}.{{ .Values.domain }}
            secretName: {{ .Release.Name }}-tls-certificate
    {{- end }}
    rules:
        - host: '{{ .Values.env }}.{{ .Values.domain }}'
          http:
              paths:
                  - path: {{ if hasKey .Values.mediaProvider "apiPrefix" }}{{ .Values.mediaProvider.apiPrefix }}/assets/media{{ else }}/assets/media{{ end }}
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: nginx
                            port:
                                number: 80
                  - path: {{ if hasKey .Values.mediaProvider "apiPrefix" }}{{ .Values.mediaProvider.apiPrefix }}/catalog{{ else }}/catalog{{ end }}
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: nginx
                            port:
                                number: 80