apiVersion: apps/v1
kind: Deployment
metadata:
    name: tada-{{ .Release.Name }}-nginx
    labels:
        app: tada-{{ .Release.Name }}-nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: tada-{{ .Release.Name }}-nginx
    template:
        metadata:
            labels:
                app: tada-{{ .Release.Name }}-nginx
        spec:
            containers:
                -   name: tada-{{ .Release.Name }}-nginx
                    image: {{ .Values.mediaProvider.nginx.imageName }}
                    ports:
                        -   containerPort: 8080
                    volumeMounts:
                        -   name: nginx-cache
                            mountPath: /opt/bitnami/nginx/cache
                        -   name: nginx-config-volume
                            mountPath: /opt/bitnami/nginx/conf/nginx.conf
                            subPath: nginx.conf
                    resources:
                        requests:
                            cpu: {{ .Values.mediaProvider.nginx.resources.requests.cpu }}
                            memory: {{ .Values.mediaProvider.nginx.resources.requests.memory }}
                        limits:
                            cpu: {{ .Values.mediaProvider.nginx.resources.limits.cpu }}
                            memory: {{ .Values.mediaProvider.nginx.resources.limits.memory }}
            volumes:
                -   name: nginx-cache
                    emptyDir: {}
                -   name: nginx-config-volume
                    configMap:
                        name: tada-{{ .Release.Name }}-nginx-configmap
                        items:
                            -   key: nginx.conf
                                path: nginx.conf
