x-environment-variables:
  &default-environment
    API_PREFIX: ""
    DELEGATED_STORAGE_RATE_LIMIT: 5
    DELEGATED_STORAGE_RATE_LIMIT_WINDOW: 30000
    NGINX_SERVICE: http://host.docker.internal:8080
    IMAGE_SERVICE: http://localhost:3001
    NGINX_INGRESS: http://localhost:8080

    VERSION: 0.0.1
    NAMESPACES: CMS,FORMS,DEV
    VALID_MIMETYPES: image/png,image/jpeg,application/pdf,image/jpg,image/webp,image/svg+xml

    DEV_ENV: true

    # GLOUTON API:
    # DELEGATED_STORAGE_HOST: http://host.docker.internal:3002
    # DELEGATED_STORAGE_READINESS_CHECK: /readiness-check
    # DELEGATED_STORAGE_GET_PATH:
    # DELEGATED_STORAGE_POST_PATH:
    # DELEGATED_STORAGE_PUT_PATH:
    # DELEGATED_STORAGE_DELETE_PATH:
    # DELEGATED_STORAGE_TOKEN: NinjaDesIles

    # S3 BACKUP :
    DELEGATED_STORAGE_READINESS_CHECK: /minio/health/live
    DELEGATED_STORAGE_HOST: http://localhost:9000

    DELEGATED_STORAGE_METHOD: S3

    S3_ENDPOINT: localhost
    S3_PORT: 9000
    S3_ACCESS_KEY: minioadmin
    S3_SECRET_KEY: minioadmin
    S3_BUCKET_NAME: media

    DUMP_FOLDER_PATH: /dumps
    REDIS_SERVICE: localhost

    HEALTHCHECK_ROUTE: /readiness-check

    PAYLOAD_MAX_SIZE: "10mb"
    BASE_TIMEOUT_MS: 1000

    ORIGINS_ALLOWED: localhost,*
    METHODS_ALLOWED: GET,POST

    USE_STRIPMETADATA: true
    TMP_FILES_PATH: './images'



services:
    redis:
        image: bitnami/redis:7.0.15-debian-12-r20
        container_name: redis_server
        command: redis-server --protected-mode no --dir /dumps
        ports:
            - '6379:6379'
        volumes:
            - ../redis/dumps:/dumps
        networks:
            - redis_net
    minio:
        image: minio/minio
        ports:
            - 9000:9000
            - 8900:8900
        environment:
            MINIO_ROOT_USER: 'minioadmin'
            MINIO_ROOT_PASSWORD: 'minioadmin'
        command: 'minio server /data/minio --console-address ":8900"'
        volumes:
            - pv-minio:/data/minio
        networks:
            - media_network
    nginx-purge:
        image: emcniece/nginx-cache-purge:1.13-alpine
        ports:
            - 8081:8081
        volumes:
            - ../nginx/nginx-purge.conf:/etc/nginx/nginx.dev.conf
        networks:
            - media_network
    nginx:
        image: bitnami/nginx:latest
        ports:
            - 8080:8080
        volumes:
            - ../nginx/nginx.conf:/opt/bitnami/nginx/conf/nginx.dev.conf
        networks:
            - media_network

volumes:
    pv-minio:
    minio:
        driver: local

networks:
    redis_net:
        driver: bridge
    media_network:
        driver: bridge
