ingress:
    nginx:
        className: nginx
        annotations:
    api:
        className: nginx
        annotations:
redis:
    imageName: bitnami/redis:7.0.15-debian-12-r20
    service: redis-service
    dumpFolderPath: '/dumps'
    storage:
        storageClassName: hostpath
    resources:
        requests:
            cpu: 200m
            memory: 128Mi  
        limits:
            cpu: 800m
            memory: 512Mi

delegatedStorage:
    rateLimitWindow: 30000
    rateLimit: 5
    connect: true
    host: 'http://minio:9000'
    routes:
        readinessCheck: '/minio/health/live'
        get: ''
        post: ''
        put: ''
        delete: ''
    accessToken: 'NinjaDesIles'
    storageMethod: 'S3'

s3:
    endpoint: 'minio'
    port: '9000'
    accessKey: 'minioadmin'
    secretKey: 'minioadmin'
    bucketName: 'media'
    storage:
        storageClassName: hostpath
        resources:
            requests:
                storage: 500Mi

mediaProvider:
    mediaToken: 'token'
    initImagesPath: ''
    initImagesNamespace: ''
    initImagesDestination: ''
    useStripMetadata: true
    imageName: 'bouyguestelecom/tada'
    imageVersion: 'api-latest'
    pvPathImage: '/images'
    service: 'http://tada-palpatine-media-ap1-media-service.palpatine-media-ap1'
    nginx:
        imageName: bitnami/nginx:latest
        resources:
            requests:
                cpu: 200m
                memory: 128Mi
            limits:
                cpu: 800m
                memory: 512Mi
    nginxPurge:
        imageName: emcniece/nginx-cache-purge:1.13-alpine
        resources:
            requests:
                cpu: 200m
                memory: 128Mi
            limits:
                cpu: 800m
                memory: 512Mi

    routes:
        healthcheck:
            get: '/readiness-check'
        file:
            get: '/assets/media/'
            post: '/upload'
            patch: ''
            delete: ''
        files:
            post: '/uploads'
            patch: ''
            delete: ''
        catalog:
            get: '/catalog'
        delegatedStorage:
            get: '/delegated-storage'
            post: '/delegated-storage'
            patch: '/delegated-storage'
            delete: '/delegated-storage'
    payloadMaxSize: '10mb'
    rateLimit:
        windowMs: 30000
        limit: 5
    originsAllowed: 'localhost,*'
    methodsAllowed: 'GET,POST'
    storage:
        storageClassName: hostpath
    resources:
        requests:
            cpu: 200m
            memory: 128Mi
        limits:
            cpu: 800m
            memory: 512Mi
        
    backupAndCleanJob:
        imageName: 'bouyguestelecom/tada'
        imageVersion: 'job-latest'
        resources:
            requests:
                cpu: 50m
                memory: 64Mi

rateLimit:
    windowMs: 30000
    limit: 5

hpa:
    replicaCountMin: 1
    replicaCountMax: 1

protocol: 'http'
env: 'media-service'
domain: '.media'
NAMESPACES_ALLOWED: 'DEV'