FROM node:18-alpine AS builder
WORKDIR /app

COPY package*.json ./
COPY . .
RUN npm set strict-ssl false && npm install

RUN npm run build

RUN mkdir -p ./api/images
WORKDIR /app/api/images
COPY ./api/images ./

FROM node:18-alpine
WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
RUN mkdir -p ./tmp/images
COPY --from=builder /app/api/images ./tmp/images 

CMD ["node", "dist/api/server.js"]