FROM node:18-alpine
WORKDIR /app

# Copier uniquement les fichiers nécessaires
COPY package*.json ./
COPY node_modules/ ./node_modules/
COPY dist/ ./dist/

# Créer le répertoire d'images
RUN mkdir -p ./tmp/images

# Exécuter l'application
CMD ["node", "dist/api/server.js"]