FROM node:18-alpine AS builder

WORKDIR /app

COPY backup-and-clean/src ./
COPY utils/logs ./utils/logs

RUN npm install --strict-ssl=false

RUN npm run build

FROM node:18-alpine

WORKDIR /app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

CMD ["node", "/app/dist/server.js"]